Update 04-deploy.yml-telegram

diff --git a/.github/workflows/04-deploy.yml b/.github/workflows/04-deploy.yml
--- a/.github/workflows/04-deploy.yml
+++ b/.github/workflows/04-deploy.yml
@@ -1,33 +1,34 @@
-name: 04 Deploy Workflow
+name: 04 Deploy Workflow Copy
 
 on:
   workflow_dispatch:
-  #workflow_run:
-  #  workflows: ["03 Build Artifact Workflow"]
-  #  types: [completed]
+
+env:
+  BASE_IMAGE: python:3.12-slim
+  IMAGE_NAME: tiny-health-app
+  CONTAINER_NAME: tiny-health-container
+  APP_PORT: 8000
 
 jobs:
-  deploy-package:
-    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
+  deploy:
     runs-on: ubuntu-latest
 
-    env:
-      BASE_IMAGE: python:3.12-slim
-      APP_PORT: 8000
-      IMAGE_NAME: tiny-health-app
-      CONTAINER_NAME: tiny-health-container
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v6
+      - name: Checkout
+        uses: actions/checkout@v4
 
-      - name: Build Docker image with args
+      - name: Create .env file
+        run: |
+          echo "APP_ENV=production" >> .env
+          echo "PORT=${APP_PORT}" >> .env
+
+      - name: Build Docker image (dynamic base)
         run: |
           docker build \
+            -f Dockerfile.prod \
             --build-arg BASE_IMAGE=${BASE_IMAGE} \
+            --build-arg APP_ENV=production \
             --build-arg APP_PORT=${APP_PORT} \
-            --build-arg IMAGE_NAME=${IMAGE_NAME} \
-            --build-arg CONTAINER_NAME=${CONTAINER_NAME} \
             -t ${IMAGE_NAME}:latest \
             .
 
@@ -35,22 +36,35 @@ jobs:
         run: |
           docker run -d \
             --name ${CONTAINER_NAME} \
+            --env-file .env \
             -p ${APP_PORT}:${APP_PORT} \
             ${IMAGE_NAME}:latest
-      - name: Show container logs
-        run: docker logs ${CONTAINER_NAME}
 
-      - name: Smoke test
+      - name: Check container is running
         run: |
-          for attempt in 1 2 3 4 5; do
-            if curl --fail --silent http://127.0.0.1:${APP_PORT}/health; then
-              exit 0
-            fi
-            echo "Waiting for app..."
-            sleep 2
-          done
-          echo "App not ready"
-          exit 1
+          docker ps
+
+          if [ "$(docker ps -q -f name=${CONTAINER_NAME})" ]; then
+            echo "Container is running ✅"
+          else
+            echo "Container is NOT running ❌"
+            docker logs ${CONTAINER_NAME}
+            exit 1
+          fi
+
+      # - name: Smoke test deployed app
+      #   # Retry a few times because app startup can take a moment.
+      #   run: |
+      #     for attempt in {1..10}; do
+      #       if curl --fail --silent http://127.0.0.1:8000/health; then
+      #         exit 0
+      #       fi
+      #       echo "Waiting for app to become ready..."
+      #       sleep 2
+      #     done
+      #     echo "App did not become ready in time."
+      #     exit 1
+
 
       - name: Cleanup
         if: always()
